#!/bin/bash
# $1 - URL
# $2 - Float
# $3 - Hide Helper
# $4 - Lock Aspect Ratio
# $5 - Click Through
# $6 - Connect Spaces
# $7 - Shadow
# $8 - Window X
# $9 - Window Y
# $10 - Window Width
# $11 - Window Height

# Set all the variables
URL=$1
WINDOWFLOAT="$2"
WINDOWHIDEHELPER="$3"
WINDOWLOCKASPECTRATIO="$4"
WINDOWCLICKTHROUGH="$5"
WINDOWCONNECTSPACES="$6"
WINDOWSHADOW="$7"

WINDOWX="$8"
WINDOWY="$9"
WINDOWWIDTH="${10}"
WINDOWHEIGHT="${11}"

# Set this to the applciation bundle for KISSWebViewer
APPLICATIONPATH="/Volumes/Storage/Applications/Selftilities/KISSWebViewer.app"

# Delete any old /tmp/ file we had
rm -r /tmp/kisswebviewer

# Write all the values into /tmp/kisswebviewer
echo -e "$URL\n$WINDOWFLOAT\n$WINDOWHIDEHELPER\n$WINDOWLOCKASPECTRATIO\n$WINDOWCLICKTHROUGH\n$WINDOWCONNECTSPACES\n$WINDOWSHADOW\n$WINDOWX\n$WINDOWY\n$WINDOWWIDTH\n$WINDOWHEIGHT" > "/tmp/kisswebviewer"

# Open a new instance of KISSWebViewer
open -n "$APPLICATIONPATH"

# Sleep for 1 second
sleep 1

# Delete the /tmp/kisswebviewer file, so if we open it again from the bundle, it doesnt load like it was opened from the terminal
rm -r /tmp/kisswebviewer